// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYV3NAJa12sTHkRdwZmo8Y-M7Nowd5LjA',
    appId: '1:413195752201:web:cfa60b14ea98943cf679d8',
    messagingSenderId: '413195752201',
    projectId: 'firstflutter-12cbf',
    authDomain: 'firstflutter-12cbf.firebaseapp.com',
    storageBucket: 'firstflutter-12cbf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlH6B28qcs3UCDhZsAsxeooghhE0dhBCs',
    appId: '1:413195752201:android:bd20ff7b9abee30ff679d8',
    messagingSenderId: '413195752201',
    projectId: 'firstflutter-12cbf',
    storageBucket: 'firstflutter-12cbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdi6CN8-WyIaiLHH4G3Fa0WgOCLEcj8LA',
    appId: '1:413195752201:ios:552083a9e02712ecf679d8',
    messagingSenderId: '413195752201',
    projectId: 'firstflutter-12cbf',
    storageBucket: 'firstflutter-12cbf.appspot.com',
    iosClientId: '413195752201-cqr649dplqu9s2btoje5qk556mug4516.apps.googleusercontent.com',
    iosBundleId: 'com.recado.instgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdi6CN8-WyIaiLHH4G3Fa0WgOCLEcj8LA',
    appId: '1:413195752201:ios:7cef643a9b71b7f7f679d8',
    messagingSenderId: '413195752201',
    projectId: 'firstflutter-12cbf',
    storageBucket: 'firstflutter-12cbf.appspot.com',
    iosClientId: '413195752201-us7pfapvqvhj187tml9t8qspqdr3m8mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
